networks:
  polygon:
    rpc_url: "https://polygon.drpc.org"
    chain_id: 137
    contracts:
      erc20:
        pol:
          address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
          decimals: "ether"
          native: true
        weth:
          address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
          decimals: "ether"
        mai:
          address: "0xa3Fa99A148fA48D14Ed51d610c367C61876997F1"
          decimals: "ether"
        dai:
          address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
          decimals: "ether"
        aave:
          address: "0xD6DF932A45C0f255f85145f286eA0b292B21C90B"
          decimals: "ether"
        qi:
          address: "0x580A84C73811E1839F75d86d75d88cCa0c241fF4"
          decimals: "ether"
        wmatic:
          address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
          decimals: "ether"
        link:
          address: "0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39"
          decimals: "ether"
        ghst:
          address: "0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7"
          decimals: "ether"
        sand:
          address: "0xBbba073C31bF03b8ACf7c28EF0738DeCF3695683"
          decimals: "ether"
        wbtc:
          address: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
          decimals: "lovelace" # hack to get 8 decimals
        uni:
          address: "0xb33EaAd8d922B1083446DC23f610c2567fB5180f"
          decimals: "ether"
        jeur:
          address: "0x4e3Decbb3645551B8A19f0eA1678079FCB33fB4c"
          decimals: "ether"
        usdc:
          address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
          decimals: "mwei"
        bal:
          address: "0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3"
          decimals: "ether"
        stmatic:
          address: "0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4"
          decimals: "ether"
        ldo:
          address: "0xC3C7d422809852031b44ab29EEC9F1EfF2A58756"
          decimals: "ether"
  optimism:
    rpc_url: "https://mainnet.optimism.io"
    chain_id: 10
    contracts:
      erc20:
        eth:
          address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
          decimals: "ether"
          native: true
        op: 
          address: "0x4200000000000000000000000000000000000042"
          decimals: "ether"
        mai:
          address: "0xdFA46478F9e5EA86d57387849598dbFB2e964b02"
          decimals: "ether"
        dai:
          address: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
          decimals: "ether"
        usdc:
          address: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"
          decimals: "mwei"
        weth:
          address: "0x4200000000000000000000000000000000000006"
          decimals: "ether"
        qi:
          address: "0x3F56e0c36d275367b8C502090EDF38289b3dEa0d"
          decimals: "ether"
        ldo:
          address: "0xFdb794692724153d1488CcdBE0C56c252596735F"
          decimals: "ether"
        velo:
          address: "0x9560e827af36c94d2ac33a39bce1fe78631088db"
          decimals: "ether"
  ethereum:
    rpc_url: "https://eth.drpc.org"
    chain_id: 1
    contracts:
      erc20:
        eth:
          address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
          decimals: "ether"
          native: true
        weth:
          address: "0xC02aaA39b223FE8D0A0E5C4F27eAD9083C756Cc2"
          decimals: "ether"
        dai:
          address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
          decimals: "ether"
        adai:
          address: "0x018008bfb33d285247A21d44E50697654f754e63"
          decimals: "ether"
        usdc:
          address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
          decimals: "mwei"
        wbtc:
          address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
          decimals: "lovelace"
        glm:
          address: "0x7DD9c5Cba05E151C895FDe1CF355C9A1D5DA6429"
          decimals: "ether"
        wsteth:
          address: "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
          decimals: "ether"
        wtau:
          address: "0x77E06c9eCCf2E797fd462A92B6D7642EF85b0A44"
          decimals: "gwei"
  arbitrum:
    rpc_url: "https://arb1.arbitrum.io/rpc"
    chain_id: 42161
    contracts:
      erc20:
        eth:
          address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
          decimals: "ether"
          native: true
        weth:
          address: "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
          decimals: "ether"
        aarb:
          address: "0x6533afac2E7BCCB20dca161449A13A32D391fb00"
          decimals: "ether"
        usdc:
          address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
          decimals: "mwei"
