networks:
  polygon:
    rpc_url: "https://polygon-rpc.com/"
    chain_id: 137
    contracts:
      swaps:
        quickswap: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
        apeswap: "0x9E31215F6421c4EED2c04116d430CaF30999680d"
        sushiswap: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
      erc20:
        weth:
          address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
          decimals: "ether"
        mai:
          address: "0xa3Fa99A148fA48D14Ed51d610c367C61876997F1"
          decimals: "ether"
        dai:
          address: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
          decimals: "ether"
        aave:
          address: "0xD6DF932A45C0f255f85145f286eA0b292B21C90B"
          decimals: "ether"
        qi:
          address: "0x580A84C73811E1839F75d86d75d88cCa0c241fF4"
          decimals: "ether"
        wmatic:
          address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
          decimals: "ether"
        glm:
          address: "0x0B220b82F3eA3B7F6d9A1D8ab58930C064A2b5Bf"
          decimals: "ether"
        link:
          address: "0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39"
          decimals: "ether"
        sand:
          address: "0xBbba073C31bF03b8ACf7c28EF0738DeCF3695683"
          decimals: "ether"
        wbtc:
          address: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"
          decimals: "lovelace" # hack to get 8 decimals
        uni:
          address: "0xb33EaAd8d922B1083446DC23f610c2567fB5180f"
          decimals: "ether"
        jeur:
          address: "0x4e3Decbb3645551B8A19f0eA1678079FCB33fB4c"
          decimals: "ether"
        usdc:
          address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
          decimals: "mwei"
        bal:
          address: "0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3"
          decimals: "ether"
        stmatic:
          address: "0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4"
          decimals: "ether"
        ldo:
          address: "0xC3C7d422809852031b44ab29EEC9F1EfF2A58756"
          decimals: "ether"
  optimism:
    rpc_url: "https://rpc.ankr.com/optimism"
    chain_id: 10
    contracts:
      erc20:
        op: 
          address: "0x4200000000000000000000000000000000000042"
          decimals: "ether"
        mai:
          address: "0xdFA46478F9e5EA86d57387849598dbFB2e964b02"
          decimals: "ether"
        dai:
          address: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
          decimals: "ether"
        weth:
          address: "0x4200000000000000000000000000000000000006"
          decimals: "ether"
        qi:
          address: "0x3F56e0c36d275367b8C502090EDF38289b3dEa0d"
          decimals: "ether"
        ldo:
          address: "0xFdb794692724153d1488CcdBE0C56c252596735F"
          decimals: "ether"
